In [47]:
from numpy import array
from openpyxl import Workbook, load_workbook
from openpyxl.compat import range
import numpy as np
import re, string
import unicodedata
#import sys
#reload(sys)
#sys.setdefaultencoding('utf-8')

ntxt = 26
elimina = 0.54 #percentatge de les paraules mes usades a eliminar
frase = 'Em dic Marc Turmo Sabater i tinc 17 anys perque vaig neixer el 13 de gener del 2002'
Afrase = frase.split()
print Afrase

['Em', 'dic', 'Marc', 'Turmo', 'Sabater', 'i', 'tinc', '17', 'anys', 'perque', 'vaig', 'neixer', 'el', '13', 'de', 'gener', 'del', '2002']


In [48]:
def remove_punctuation ( text ):
    return re.sub('[%s]' % re.escape(string.punctuation), '', text)

def remove_punctuation2 (text):
    for char in "'-.,\n()":
        text=text.replace(char,' ')
    return text

In [49]:
wb = load_workbook(filename = 'C:\Users\WORK\@TREBALL_RECERCA\prova.xlsx')
ws = wb.active
sheet_ranges = wb['txt']
text = np.empty(ntxt, dtype="U2000")
for fila in range(1, ntxt+1):
    frase = ws.cell(fila, column=1).value
    frase = remove_punctuation2(frase)
    frase = frase.lower()
    #frase = unicode(frase, "utf-8")
    frase = unicodedata.normalize('NFKD', frase).encode('ASCII', 'ignore')
    
    print fila
    print frase
    #string = unicode(frase, 'utf8')
    text [fila-1] = frase
    
print text

1
messi se ha unido junto al resto de internacionales que han regresado de sus selecciones  ter stegen  semedo  rakitic  todibo  alena  umtiti y vermaelen   por su parte  luis suarez es todavia duda para el derbi barcelones  si bien realizo parte de la sesion con sus companeros  el delantero uruguayo  que habia realizado trabajo especifico durante la semana  mejora favorablemente del esguince sufrido en el tobillo derecho en la ultima jornada contra el betis  
2
el president de la generalitat quim torra  ha esperado apenas unas horas para contrarrestar la querella que le ha interpuesto la fiscalia por desobediencia en relacion a la polemica de los lazos amarillos con otra contra la junta electoral central  jec  por un supuesto delito de prevaricacion  tras recibir la denuncia del ministerio publico  el jefe del ejecutivo catalan ha lamentado que  queda claro que la represion no se detiene   que persiste la persecucion politica  y que espana  es incapaz de tolerar la discrepancia politi

In [50]:
def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

### Aqui construim un diccionari per cada text amb el numero de vegades que surt cada paraula

In [51]:
dicttext = [dict() for x in range(ntxt)]
for fila in range(0, ntxt):
    dicttext[fila] = word_count(text[fila])

print dicttext

[{u'el': 4, u'favorablemente': 1, u'alena': 1, u'messi': 1, u'por': 1, u'al': 1, u'durante': 1, u'regresado': 1, u'barcelones': 1, u'habia': 1, u'en': 2, u'semana': 1, u'sufrido': 1, u'ter': 1, u'realizado': 1, u'es': 1, u'junto': 1, u'jornada': 1, u'parte': 2, u'han': 1, u'la': 3, u'duda': 1, u'del': 1, u'si': 1, u'contra': 1, u'bien': 1, u'sus': 2, u'mejora': 1, u'resto': 1, u'companeros': 1, u'trabajo': 1, u'todibo': 1, u'para': 1, u'delantero': 1, u'internacionales': 1, u'de': 3, u'ultima': 1, u'que': 2, u'realizo': 1, u'luis': 1, u'stegen': 1, u'ha': 1, u'esguince': 1, u'derecho': 1, u'semedo': 1, u'umtiti': 1, u'derbi': 1, u'selecciones': 1, u'suarez': 1, u'uruguayo': 1, u'betis': 1, u'su': 1, u'tobillo': 1, u'vermaelen': 1, u'unido': 1, u'se': 1, u'especifico': 1, u'y': 1, u'todavia': 1, u'sesion': 1, u'rakitic': 1, u'con': 1}, {u'el': 2, u'claro': 1, u'en': 1, u'polemica': 1, u'persecucion': 1, u'lazos': 1, u'politica': 2, u'por': 2, u'contrarrestar': 1, u'querella': 1, u'discr

### Aqui construim el diccionari global amb totes les paraules i el nombre total de vegades de cadascuna
### Comptem el nombre total de paraules
### Eliminem del diccionari global el % establert

In [52]:
diccionaritotal = dict()
for fila in range(0, ntxt):
    diccionaritotal.update(dicttext[fila])
for word in diccionaritotal:
    diccionaritotal.update({word: 0})    
    
for fila in range(0, ntxt):
    for word in dicttext [fila]:
        x = dicttext[fila].get(word)
        y = diccionaritotal.get(word)
        x = x + y
        diccionaritotal.update({word: x})

print diccionaritotal


{u'senalado': 1, u'all': 1, u'resoluciones': 1, u'asombro': 1, u'cuartos': 1, u'candidatura': 1, u'toalla': 1, u'messi': 8, u'bavaro': 1, u'azulgrana': 2, u'prolongo': 1, u'evidente': 1, u'tiende': 1, u'laura': 1, u'lider': 2, u'gane': 1, u'dijo': 1, u'toni': 1, u'mucho': 1, u'pedro': 1, u'junio': 2, u'impuso': 1, u'dicho': 3, u'presentarse': 1, u'quienes': 1, u'otra': 2, u'aun': 1, u'0': 1, u'psoe': 5, u'describiria': 1, u'under': 1, u'terror': 1, u'votos': 2, u'articular': 1, u'metafisico': 1, u'auge': 1, u'empresario': 1, u'aparca': 1, u'reforma': 1, u'europeos': 1, u'convocante': 1, u'rtve': 3, u'gracias': 1, u'primeros': 1, u'llama': 1, u'govern': 3, u'casa': 2, u'pueblo': 1, u'sant': 2, u'votacion': 1, u'tenia': 1, u'peor': 1, u'permitira': 2, u'trajo': 1, u'optimistas': 1, u'genialidad': 1, u'legitimado': 1, u'presentes': 1, u'subcampeon': 1, u'larga': 1, u'red': 1, u'especifico': 1, u'espanol': 5, u'meses': 1, u'atletico': 3, u'temporada': 3, u'salah': 1, u'balaidos': 1, u'hora

### Comptem el nombre total de paraules
### Eliminem del diccionari global el % establert

In [53]:
contt = 0
for word in diccionaritotal:
        y = diccionaritotal.get(word)
        contt = contt + y
print contt

llindar = contt * elimina
print llindar

import operator
sorted_dict = sorted(diccionaritotal.items(), key=operator.itemgetter(1), reverse=True)
print sorted_dict
longitud = len(sorted_dict)
print longitud
print ' '

x = sorted_dict[0][1]
llindar=llindar-x
while (llindar > 0):
    longitud=longitud-1
    sorted_dict.pop(0)
    x = sorted_dict[0][1]
    llindar=llindar-x
                        
print sorted_dict
longitud = len(sorted_dict)
print longitud
print ' '


2874
1551.96
[(u'de', 170), (u'la', 143), (u'el', 120), (u'en', 98), (u'que', 84), (u'y', 70), (u'a', 61), (u'del', 53), (u'ha', 38), (u'los', 37), (u'por', 33), (u'se', 30), (u'su', 29), (u'un', 28), (u'con', 27), (u'las', 22), (u'al', 22), (u'no', 22), (u'una', 18), (u'para', 16), (u'despues', 13), (u'mas', 12), (u'como', 12), (u'es', 12), (u'sus', 10), (u'pero', 10), (u'este', 10), (u'le', 9), (u'contra', 9), (u'han', 9), (u'messi', 8), (u'dos', 8), (u'torra', 7), (u'partidos', 7), (u'jordi', 7), (u'todo', 7), (u'pp', 7), (u'liverpool', 7), (u'sanchez', 6), (u'segun', 6), (u'esta', 6), (u'ante', 6), (u'martes', 6), (u'psoe', 5), (u'espanol', 5), (u'sobre', 5), (u'sin', 5), (u'liga', 5), (u'nunca', 5), (u'final', 5), (u'cuatro', 5), (u'ciudadanos', 5), (u'habia', 5), (u'lo', 5), (u'partido', 5), (u'espana', 5), (u'son', 5), (u'politica', 5), (u'congreso', 5), (u'identidad', 4), (u'presidente', 4), (u'tras', 4), (u'elecciones', 4), (u'he', 4), (u'entre', 4), (u'anos', 4), (u'extrema',

In [54]:
#llistatotal = list(diccionaritotal)
llistatotal = [i[0] for i in sorted_dict]  
llistatxt = np.empty((ntxt),dtype=list)

#eliminem de cada text les paraules mes usades que ja haviem eliminat a la llista total
for fila in range (0, ntxt):
    llistatxt[fila] = list(dicttext[fila])
    llistatxt[fila].sort() 
    for word in llistatxt[fila]:
        if word not in llistatotal:
            llistatxt[fila].remove(word)

llistatotal.sort()
print llistatotal
len(llistatotal)
# print llistatxt


[u'"en', u'"independiente', u'0', u'00', u'123', u'15', u'155', u'2', u'2016', u'2017', u'2018', u'2021', u'21', u'24', u'250', u'26', u'3', u'32', u'33', u'35', u'39o', u'4', u'42', u'50', u'57', u'6', u'600', u'65', u'66', u'85', u'9', u'abiertamente', u'abierto', u'abordado', u'absoluta', u'acabado', u'acabo', u'acceso', u'aceptar', u'acerca', u'acn', u'acordado', u'acordaron', u'actitud', u'actividad', u'actuacion', u'actual', u'acuerdo', u'acuerdos', u'acumula', u'acumulaba', u'acusandose', u'adecuacion', u'adios', u'admirado', u'adquirio', u'advertia', u'aficion', u'aguarda', u'ahi', u'ahora', u'albert', u'alcanzo', u'alegrias', u'alena', u'alimenta', u'alineacion', u'all', u'altibajos', u'altura', u'amarillos', u'ambito', u'ambos', u'amenaza', u'amparo', u'ana', u'anfield', u'ano', u'ansiedad', u'antes', u'antesala', u'antologico', u'anuncia', u'anunciado', u'anuncio', u'aparca', u'aparece', u'aparecido', u'apenas', u'aplique', u'apoyo', u'aprobado', u'apuesta', u'apuntado', u'a

1102

In [55]:
arrayllistatotal = np.asarray(llistatotal,dtype="U40") 
print arrayllistatotal
len(arrayllistatotal)

[u'"en' u'"independiente' u'0' ... u'xenofobos' u'yo' u'zaguero']


1102

In [56]:
longitud = len(llistatotal)
print longitud
token = np.zeros([ntxt, longitud], dtype = int)

for fila in range(0, ntxt):
    for word in range(0, longitud):
        if arrayllistatotal[word] in llistatxt[fila]: 
            token[fila, word] = 1
print token[0]
print token

1102
[0 0 0 ... 0 0 0]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [58]:
from numpy import exp, array, random, dot


class NeuralNetwork():

    def __init__(self):
        random.seed(1)
        self.synaptic_weights = 2 * random.random((1102,1)) - 1   #Cal calcular el 1171 per programa PENDENT
        
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in xrange(number_of_training_iterations):
            output = self.think(training_set_inputs)
            print(output)
            error = training_set_outputs - output
            #print  self.synaptic_weights[0]
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))
            self.synaptic_weights += adjustment

    def think(self, inputs):
        return self.__sigmoid(dot(inputs, self.synaptic_weights))

if __name__ == "__main__":
    neural_network = NeuralNetwork()
    #print "Random starting synaptic weights: "
    #print neural_network.synaptic_weights
    training_set_inputs = token[0:20]
    training_set_outputs =  array([[1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0]]).T
    neural_network.train(training_set_inputs, training_set_outputs, 100)
    print "New synaptic weights after training: "
    #print neural_network.synaptic_weights
    print "Considering new situation [1, 0, 0] -> ?: "
    print neural_network.think(token[21])
    print neural_network.think(token[22])
    print neural_network.think(token[23])
    print neural_network.think(token[24])
    print neural_network.think(token[25])
    print neural_network.think(token[20])
    

[[0.00409732]
 [0.1752016 ]
 [0.16021123]
 [0.45442874]
 [0.64348749]
 [0.25619184]
 [0.3910004 ]
 [0.06916195]
 [0.7449899 ]
 [0.9885937 ]
 [0.57213248]
 [0.90110028]
 [0.09747775]
 [0.39913597]
 [0.05796449]
 [0.29147252]
 [0.00501741]
 [0.11250687]
 [0.98410389]
 [0.97229694]]
[[0.00482949]
 [0.0560056 ]
 [0.04286607]
 [0.0067409 ]
 [0.97504406]
 [0.14869794]
 [0.04720585]
 [0.05967133]
 [0.01308112]
 [0.98694494]
 [0.99131204]
 [0.12593463]
 [0.04397412]
 [0.99989684]
 [0.70094581]
 [0.99584986]
 [0.02691334]
 [0.93825893]
 [0.94307316]
 [0.87687089]]
[[0.00595019]
 [0.03714735]
 [0.02874547]
 [0.00601857]
 [0.97822935]
 [0.09803263]
 [0.04416528]
 [0.04735859]
 [0.01133803]
 [0.98737402]
 [0.99216725]
 [0.06666147]
 [0.03866359]
 [0.99990828]
 [0.99217224]
 [0.99600157]
 [0.19270215]
 [0.95249368]
 [0.25447984]
 [0.10540965]]
[[0.00956766]
 [0.03127675]
 [0.02250326]
 [0.00591226]
 [0.97864723]
 [0.08282687]
 [0.04692453]
 [0.03976497]
 [0.01072589]
 [0.99118911]
 [0.9945328 ]
 [0