In [1]:
from numpy import array
from openpyxl import Workbook, load_workbook
from openpyxl.compat import range
import numpy as np
import re, string
import unicodedata
#import sys
#reload(sys)
#sys.setdefaultencoding('utf-8')

ntxt = 1000                # maxim de files que pot tenir excel
elimina = 0.40           #percentatge de les paraules mes usades a eliminar
percentatge_train = 0.80   #percentatge de files que usem per a entrenar el model


In [2]:
def remove_punctuation ( text ):
    return re.sub('[%s]' % re.escape(string.punctuation), '', text)

def remove_punctuation2 (text):
    for char in "'-.,\n()":
        text=text.replace(char,' ')
    return text

In [3]:
wb = load_workbook(filename = 'C:\Users\WORK\@TREBALL_RECERCA\product_sentiment4.xlsx')
ws = wb.active
sheet_ranges = wb['txt']
text = np.empty(1000, dtype="U2000")
tipus = np.empty(1000, dtype=int)
for fila in range(0, ntxt):
    frase = ws.cell(row=fila+1, column=1).value
    frase = remove_punctuation2(frase)
    frase = frase.lower()
    #frase = unicode(frase, "utf-8")
    frase = unicodedata.normalize('NFKD', frase).encode('ASCII', 'ignore')
    if frase == 'final' : 
        ntxt = fila 
        break
    print fila
    print frase
    #string = unicode(frase, 'utf8')
    text [fila] = frase
    tipus[fila] = ws.cell(row=fila+1, column=2).value
print text
print tipus
print ntxt

0
he likes chewing on all the parts especially the head and the ears! it has helped when he has been cranky because of teething  great purchase!
1
there really should be a large warning on the box   sheesh  in 2011 with so many anaphylactic latex allergies and latex being an allergy that is caused by repeated exposure why in the world would someone think an all latex teether was a good idea for a baby??  this baby teether could have quite easily killed mommy and there was no warning on the packaging that is made of latex 
2
my baby seems to like this toy  but i could see how it would be a problem if he got it jammed in his mouth  this has not hapened yet  but i could see how it easily could  also the paint and some of the rubber seems to have already come off and my baby does not even have teeth yet
3
first  i should qualify this by stating that my children have never been contented by the normal baby soothers  swings  jumpers  bouncy seats   so it does not entirely surprise me that th

326
my daughter chewed on it a little  but actually ended up preferring metal teething rings  she liked playing with it more than nibbling on it 
327
my 6 month old loved it and reached for sophie the moment she saw it and promptly started chewing on it so vulli  must have gotten something right about the teether  her 3 year old twin cousins were playing n squeaking it as well   so all in all a good purchase   both for teething n play 
328
my 4 5 months little daughter love this teether very much and like to bytes it a lot at her age now 
329
cute teether  easy to clean  seems like every mom has one now! my son likes it  doesn t have to have it 
330
we just got our adorable sophie this week and my 4 & 1/2 month old daughter loves it  i m sure there are other great teethers out there but sophie is easy for chubby hands to grab and she has lots of long or nubby bits to chew on   whatever baby is in the mood for   our daughter smiles every time she sees her sophie and is content to gnaw o

577
my 6 month old grandson loves this giraffe  whether he is chewing on it or smacking it around to make it squeak  it s very durable and soft 
578
sophie is a little expensive  but worth every penny  my son s pediatrician recommended her and she has saved our ears and sanity    and my baby s smiles  on numerous occasions  my husband tried to buy another for our trip to europe but they were out of stock  we treat sophie like she is made of gold  my son is 5 months old  so no teeth yet  but he likes to bite while working out gas  sophie is fantastic for this  as well as being a great toy  she is in the top three as far as he s concerned  we are still trying to get another    get sophie while you can!
579
i don t know why  but our son  9 months old now  loves this toy  most of the items he liked at 3 months old barely hold his attention for more than 2 minutes now  but sophie is still a popular item  especially for chewing and teething  it is one of the only older toys that still make h

[u'he likes chewing on all the parts especially the head and the ears! it has helped when he has been cranky because of teething  great purchase!'
 u'there really should be a large warning on the box   sheesh  in 2011 with so many anaphylactic latex allergies and latex being an allergy that is caused by repeated exposure why in the world would someone think an all latex teether was a good idea for a baby??  this baby teether could have quite easily killed mommy and there was no warning on the packaging that is made of latex '
 u'my baby seems to like this toy  but i could see how it would be a problem if he got it jammed in his mouth  this has not hapened yet  but i could see how it easily could  also the paint and some of the rubber seems to have already come off and my baby does not even have teeth yet'
 u'first  i should qualify this by stating that my children have never been contented by the normal baby soothers  swings  jumpers  bouncy seats   so it does not entirely surprise me 

In [4]:
def word_count(str):
    counts = dict()
    words = str.split()

    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

### Aqui construim un diccionari per cada text amb el numero de vegades que surt cada paraula

In [5]:
dicttext = [dict() for x in range(ntxt)]
for fila in range(0, ntxt):
    dicttext[fila] = word_count(text[fila])

print dicttext

[{u'and': 1, u'all': 1, u'because': 1, u'it': 1, u'helped': 1, u'ears!': 1, u'teething': 1, u'when': 1, u'been': 1, u'parts': 1, u'chewing': 1, u'has': 2, u'head': 1, u'cranky': 1, u'purchase!': 1, u'he': 2, u'on': 1, u'great': 1, u'especially': 1, u'of': 1, u'the': 3, u'likes': 1}, {u'and': 2, u'all': 1, u'being': 1, u'caused': 1, u'is': 2, u'allergy': 1, u'box': 1, u'an': 2, u'packaging': 1, u'warning': 2, u'have': 1, u'in': 2, u'sheesh': 1, u'really': 1, u'would': 1, u'no': 1, u'allergies': 1, u'there': 2, u'teether': 2, u'was': 2, u'should': 1, u'that': 2, u'anaphylactic': 1, u'2011': 1, u'mommy': 1, u'killed': 1, u'be': 1, u'someone': 1, u'on': 2, u'why': 1, u'of': 1, u'idea': 1, u'repeated': 1, u'baby': 1, u'world': 1, u'quite': 1, u'with': 1, u'by': 1, u'exposure': 1, u'a': 3, u'latex': 4, u'made': 1, u'for': 1, u'this': 1, u'many': 1, u'could': 1, u'large': 1, u'good': 1, u'so': 1, u'easily': 1, u'baby??': 1, u'the': 3, u'think': 1}, {u'and': 2, u'already': 1, u'paint': 1, u'al

### Aqui construim el diccionari global amb totes les paraules i el nombre total de vegades de cadascuna
### Comptem el nombre total de paraules
### Eliminem del diccionari global el % establert

In [6]:
diccionaritotal = dict()
for fila in range(0, ntxt):
    diccionaritotal.update(dicttext[fila])
for word in diccionaritotal:
    diccionaritotal.update({word: 0})    
    
for fila in range(0, ntxt):
    for word in dicttext [fila]:
        x = dicttext[fila].get(word)
        y = diccionaritotal.get(word)
        x = x + y
        diccionaritotal.update({word: x})

print diccionaritotal


{u'secondly': 1, u'better!': 1, u'limited': 1, u'saver': 2, u'saves': 1, u'ever!': 4, u'yellow': 1, u'gums?additionally': 1, u'four': 22, u'prices': 1, u'sleep': 1, u'contains': 2, u'ever:': 1, u'saved': 3, u'poorly': 1, u'expensive!': 1, u'whose': 1, u'patches': 1, u'stinky': 3, u'sweetest': 1, u'seriously': 5, u'looooves': 1, u'up!': 2, u'presents': 2, u'under': 8, u'teaching': 1, u'sorry': 1, u'$40': 1, u'worth': 127, u'fists': 2, u'"girlfriend': 1, u'risk': 5, u'giraffe!!!': 1, u'blanket': 1, u'internet': 1, u'sellers': 1, u'smack': 1, u'definetly': 1, u'every': 76, u'uncoordinated': 1, u'emanate': 1, u'doubts': 2, u'internally': 1, u'prize': 1, u'obstruction': 1, u'wooden': 2, u'cons:': 2, u'clings': 1, u'companies': 1, u'solution': 1, u'frozen': 4, u'mawing': 1, u'deter': 1, u'gift!!!': 1, u'havea': 1, u'commented': 3, u'clothes': 1, u'enjoy': 12, u'chew': 209, u'me!': 2, u'infancy': 2, u'her!': 19, u'horn': 2, u'tires': 2, u'surrounding': 2, u'second': 24, u'sooth': 2, u'availab

### Comptem el nombre total de paraules
### Eliminem del diccionari global el % establert

In [7]:
contt = 0
for word in diccionaritotal:
        y = diccionaritotal.get(word)
        contt = contt + y
print contt

llindar = contt * elimina
print llindar

import operator
sorted_dict = sorted(diccionaritotal.items(), key=operator.itemgetter(1), reverse=True)
print sorted_dict
longitud = len(sorted_dict)
print longitud
print ' '

x = sorted_dict[0][1]
llindar=llindar-x
while (llindar > 0):
    longitud=longitud-1
    sorted_dict.pop(0)
    x = sorted_dict[0][1]
    llindar=llindar-x
                        
print sorted_dict
longitud = len(sorted_dict)
print longitud
print ' '


53935
21574.0
[(u'it', 2129), (u'the', 1806), (u'and', 1649), (u'i', 1608), (u'to', 1380), (u'a', 1269), (u'is', 1137), (u'my', 991), (u'for', 864), (u'this', 837), (u'sophie', 676), (u'she', 661), (u'her', 623), (u'of', 611), (u'on', 597), (u'toy', 521), (u's', 510), (u'that', 504), (u'was', 500), (u'but', 479), (u'he', 479), (u'in', 448), (u'baby', 426), (u'with', 383), (u'loves', 379), (u'so', 367), (u't', 360), (u'have', 333), (u'as', 324), (u'not', 313), (u'one', 311), (u'when', 306), (u'teething', 290), (u'we', 288), (u'old', 265), (u'has', 249), (u'his', 232), (u'little', 230), (u'son', 230), (u'just', 225), (u'daughter', 221), (u'all', 217), (u'months', 211), (u'like', 210), (u'chew', 209), (u'teether', 208), (u'at', 191), (u'giraffe', 188), (u'be', 183), (u'about', 180), (u'very', 178), (u'had', 177), (u'can', 174), (u'great', 173), (u'love', 170), (u'you', 170), (u'are', 157), (u'from', 157), (u'would', 153), (u'dog', 153), (u'month', 142), (u'bought', 140), (u'our', 139), (u

In [8]:
#llistatotal = list(diccionaritotal)
llistatotal = [i[0] for i in sorted_dict]  
llistatxt = np.empty((ntxt),dtype=list)

#eliminem de cada text les paraules mes usades que ja haviem eliminat a la llista total
for fila in range (0, ntxt):
    llistatxt[fila] = list(dicttext[fila])
    llistatxt[fila].sort() 
    for word in llistatxt[fila]:
        if word not in llistatotal:
            llistatxt[fila].remove(word)

llistatotal.sort()
print llistatotal
len(llistatotal)
# print llistatxt


[u'!', u'!!', u'!!!', u'!i', u'"', u'"amazing"', u'"are', u'"baby', u'"back', u'"car"', u'"chew', u'"chew"', u'"choking', u'"choking"', u'"classic', u'"dog', u'"gagging"', u'"get', u'"girlfriend', u'"glorified', u'"go', u'"gumming"', u'"gums"', u'"hello', u'"hip', u'"hug"', u'"i', u'"imported', u'"in', u'"ingredients"', u'"issue"', u'"it', u'"jealously', u'"natural', u'"off"', u'"peekaboo"', u'"pet"', u'"play"', u'"poor"', u'"rubbery"', u'"seventeen', u'"soft"', u'"sophie', u'"sophie"', u'"squeak', u'"steal"', u'"talk"', u'"teether"', u'"teethers"', u'"that', u'"to', u'"toy', u'"tried"', u'"voice"', u'"why', u'"write', u'"yes', u'"you', u'#1', u'#2', u'#8', u'$', u'$!', u'$$', u'$$$', u'$1', u'$10', u'$12', u'$15', u'$16', u'$16!', u'$17', u'$18', u'$19', u'$2', u'$20', u'$20!', u'$20+', u'$21', u'$22', u'$25', u'$3', u'$30', u'$4', u'$40', u'$5', u'$8', u'$[', u'&', u'&#128522;', u'&#34;chew', u'&#34;chew&#34;', u'&#34;dirty&#34;', u'&#34;every', u'&#34;green&#34;', u'&#34;here', u'&#

3887

In [9]:
arrayllistatotal = np.asarray(llistatotal,dtype="U40") 
print arrayllistatotal
len(arrayllistatotal)

[u'!' u'!!' u'!!!' ... u'zoo' u'~' u'~$15']


3887

In [10]:
longitud = len(llistatotal)
print longitud
token = np.zeros([ntxt, longitud], dtype = int)

for fila in range(0, ntxt):
    for word in range(0, longitud):
        if arrayllistatotal[word] in llistatxt[fila]: 
            token[fila, word] = 1
print token[0]
print token

3887
[0 0 0 ... 0 0 0]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
from numpy import exp, array, random, dot


class NeuralNetwork():

    def __init__(self):
        random.seed(1)
        self.synaptic_weights = 2 * random.random((longitud,1)) - 1   #Cal calcular el 1171 per programa PENDENT
        
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in xrange(number_of_training_iterations):
            output = self.think(training_set_inputs)
            #print(output)
            error = training_set_outputs - output
            #print  self.synaptic_weights
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))
            #print(adjustment)
            self.synaptic_weights += adjustment

    def think(self, inputs):
        return self.__sigmoid(dot(inputs, self.synaptic_weights))
#wb = load_workbook(filename = 'C:\Users\WORK\@TREBALL_RECERCA\prova.xlsx')
#ws = wb.active
#sheet_ranges = wb['txt']
#text = np.empty(ntxt, dtype="U2000")
    
if __name__ == "__main__":
    neural_network = NeuralNetwork()
    #print "Random starting synaptic weights: "
    #print neural_network.synaptic_weights
    train = int(ntxt * percentatge_train)
    print train
    training_set_inputs = token[0:train]
    training_set_outputs = array([tipus[0:train]]).T
    print training_set_outputs
    #training_set_outputs =  array([[1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0]]).T
    neural_network.train(training_set_inputs, training_set_outputs, 1000)
    #print "New synaptic weights after training: "
    #print neural_network.synaptic_weights
       

623
[[0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 

In [12]:
ok = 0
nook = 0
print train
print ntxt
for i in range(train+1, ntxt): 
    print neural_network.think(token[i])
    print text[i]
    print tipus[i]
    if (neural_network.think(token[i])>0.5 and tipus[i]==1) or (neural_network.think(token[i])<0.5 and tipus[i]==0):
        ok += 1
    else:
        nook += 1
print ok
print nook

623
779
[1.26374127e-51]
my 6 month old daughter loves sophie  she has so many places to chew on and is easy for her little hands to hold on to  she chews on her legs and ears and nose  but even more than that she likes to grab sophie around her neck  somewhat disturbing to see sometimes  and squeeze her repeatedly to hear the squeak! the squeak was a problem at first because my dog thought the toy was for her  when my sister visits with her young husky  we have to keep sophie away because the husky tries to steal it from the baby! my daughter loves the attention from the dogs so she thinks it s great  but i could see where it would be a problem if you have a younger dog who might be more aggressive about taking sophie away  i was slightly worried at first from the reviews about sophie s legs being a choking hazard  but i haven t noticed that at all  my daughter might have gagged on one of the legs at first  but she gags on her own hands more than she does with sophie  and gagging is c

[4.39404265e-11]
my baby is more interested in any other teether  or clothes  i trust on line reviews  and successfully bought so many interesting toys except this one  it is a waste of money 
1
[9.40610964e-10]
maybe i got defective one   baby was chewing on it and the color was coming off    my baby s mouth and around her mouth was orange from the color from the giraffe    we stopped using it 
1
[9.04760643e-12]
the sophie giraffe has a very strong rubber odor and my son doesnt like it  also  due to the texture it picks up ever the tiniest of dirt or hair and is hard to clean 
1
[1.49522875e-06]
even though the product is sold guaranteeing that it would never discolor  it did after 3 months of use  i expect to receive a replacement or a refund 
1
119
36


In [13]:
print neural_network.think(token[5])
print text[5]
print tipus[5]

[3.288164e-35]
i was intrigued with the idea of sophie the giraffe  her story and the fact that she carries a nearly $20 price tag  so wanting to know what the hype was all about  i purchased her for my 21/2 month old baby boy  as of right now  he has no interest in her  he doesn t find her interesting to look at and is not teething so her main purpose of use hasn t been tested yet  i do not believe i will be able to test her out with my son either as the paint is already peeling off sophie s head were her horns are  my other complaint is that dirt/dust clings to her  to me  she is nothing but a glorified puppy chew toy  the size of my hand   but at least i know what the hype is all about and now  sophie and now an on going joke between my girl friends and i  the $20 puppy chew toy i bought for my baby  
1
