In [33]:

from numpy import exp, array, random, dot
from openpyxl import Workbook
from openpyxl.compat import range
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
import sklearn.linear_model

%matplotlib inline

wb = Workbook()
ws = wb.active
ws.title = "Random"
dest_filename = 'grafica4.xlsx'


class NeuralNetwork():

    def __init__(self):

        # Seed the random number generator, so it generates the same numbers

        # every time the program runs.

        random.seed(3)
        self.row = 1

        ws.cell(self.row, column=1).value = "Y"
        ws.cell(self.row, column=2).value = "0"
        ws.cell(self.row, column=3).value = "1"
        ws.cell(self.row, column=4).value = "1"
        ws.cell(self.row, column=5).value = "0"
        ws.cell(self.row, column=6).value = "w1"
        ws.cell(self.row, column=7).value = "w2"
        ws.cell(self.row, column=8).value = "w3"
        ws.cell(self.row, column=9).value = "err1"
        ws.cell(self.row, column=10).value = "err2"
        ws.cell(self.row, column=11).value = "err3"
        ws.cell(self.row, column=12).value = "err4"
        ws.cell(self.row, column=13).value = "ERRORT"
        
        self.error_ant=100


        # We model a single neuron, with 3 input connections and 1 output connection.

        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1

        # and mean 0.

        self.synaptic_weights = 2 * random.random((3, 1)) - 1
        
        self.final_weights=self.synaptic_weights
 

    # The Sigmoid function, which describes an S shaped curve.

    # We pass the weighted sum of the inputs through this function to

    # normalise them between 0 and 1.

    def __sigmoid(self, x):

        return 1 / (1 + exp(-x))

 

    # The derivative of the Sigmoid function.

    # This is the gradient of the Sigmoid curve.

    # It indicates how confident we are about the existing weight.

    def __sigmoid_derivative(self, x):

        return x * (1 - x)

 

    # We train the neural network through a process of trial and error.

    # Adjusting the synaptic weights each time.

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):

        for iteration in xrange(number_of_training_iterations):

            # Pass the training set through our neural network (a single neuron).

            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output

            # and the predicted output).

            error = training_set_outputs - output
            
            # POTSER CAL FER LA SUMA EN VALOR ABSOLUT SI NO ES COMPENSEN
            #errort = error[0]+error[1]+error[2]+error[3]
            #print  self.synaptic_weights[0]
            #ws.append(errort[0])
            
            self.row+=1
            ws.cell(self.row, column=1).value = "y"
            t1=output[0]
            t2=output[1]
            t3=output[2]
            t4=output[3]
            ws.cell(self.row, column=2).value = t1[0]
            ws.cell(self.row, column=3).value = t2[0]
            ws.cell(self.row, column=4).value = t3[0]
            ws.cell(self.row, column=5).value = t4[0]
            
            w1=self.final_weights[0]
            w2=self.final_weights[1]
            w3=self.final_weights[2]
            ws.cell(self.row, column=6).value = w1[0]
            ws.cell(self.row, column=7).value = w2[0]
            ws.cell(self.row, column=8).value = w3[0]
            
            e0=error[0]
            e1=error[1]
            e2=error[2]
            e3=error[3]
            ws.cell(self.row, column=9).value = e0[0]
            ws.cell(self.row, column=10).value = e1[0]
            ws.cell(self.row, column=11).value = e2[0]
            ws.cell(self.row, column=12).value = e3[0]
            
            errorT = (error[0])**2 + (error[1])**2 + (error[2])**2 + (error[3])**2
            self.errorF = errorT/4
            
            
            # Multiply the error by the input and again by the gradient of the Sigmoid curve.

            # This means less confident weights are adjusted more.

            # This means inputs, which are zero, do not cause changes to the weights.
            
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            if errorT < self.error_ant:
                self.error_ant = errorT
                self.final_weights = self.synaptic_weights
                print self.final_weights
            self.synaptic_weights = 20 * random.random((3, 1)) - 10         
            
            et=self.error_ant/4
            ws.cell(self.row, column=13).value = et[0]

 

    # The neural network thinks.

    def think(self, inputs):

        # Pass inputs through our neural network (our single neuron).

        return self.__sigmoid(dot(inputs, self.synaptic_weights))

 

if __name__ == "__main__":

 

    #Intialise a single neuron neural network.

    neural_network = NeuralNetwork()

 

    print "Random starting synaptic weights: "

    print neural_network.synaptic_weights

 

    # The training set. We have 4 examples, each consisting of 3 input values

    # and 1 output value.

    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])

    training_set_outputs = array([[0, 1, 1, 0]]).T

    
    # Train the neural network using a training set.

    # Do it 10,000 times and make small adjustments each time.

    neural_network.train(training_set_inputs, training_set_outputs, 10000)                        

 

    print "New synaptic weights after training: "

    print neural_network.final_weights

    print "Error final"
    print neural_network.error_ant


    # Test the neural network with a new situation.

    print "Considering new situation [1, 0, 0] -> ?: "

    print neural_network.think(array([1, 0, 0]))
    
    wb.save(filename = dest_filename)
    

Random starting synaptic weights: 
[[ 0.10159581]
 [ 0.41629565]
 [-0.41819052]]
[[ 0.10159581]
 [ 0.41629565]
 [-0.41819052]]
[[ 3.06821805]
 [ 1.15681525]
 [-2.76870474]]
[[ 7.21067826]
 [ 1.72505809]
 [-4.33024275]]
[[ 7.86729543]
 [ 1.05232693]
 [-4.35897315]]
[[ 9.12879021]
 [ 0.76236845]
 [-4.35709907]]
[[ 9.1503794 ]
 [ 0.86804787]
 [-5.24292632]]
[[ 9.7414504 ]
 [-0.09060706]
 [-5.49182565]]
[[ 9.55236162]
 [ 0.62732301]
 [-4.98460269]]
New synaptic weights after training: 
[[ 9.55236162]
 [ 0.62732301]
 [-4.98460269]]
Error final
[0.0003422]
Considering new situation [1, 0, 0] -> ?: 
[0.97579946]
